name: A workflow to trigger review requests to teams on pushes or PRs to master where the readme has changed.
on: 
  pull_request:
    paths: 
      - 'README.md'
  push:
    paths: 
      - 'README.md'
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Alex"
